language: python

python:
  - "3.5.2"

services:
  - postgresql

install:
  - pip install -r requirements.txt

env:
  - DB = postgres USER = postgres PASSWORD = 'python' export APP_SETTINGS =  'test_config.cfg'

before_script:
  - psql -c "CREATE DATABASE RideMyWay;" -U postgres

script:
  - pytest  --cov=app 
  - coveralls

after_success:
  - coveralls